version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Zipping function..."
      - zip -r lambda.zip index.js node_modules package.json

  post_build:
    commands:
      - echo "Updating AWS Lambda..."
      - aws lambda update-function-code --function-name web-app-abhigyan --zip-file fileb://lambda.zip

artifacts:
  files:
    - lambda.zip
